### ISSUE TITLE
Many `Unable to parse log line:` show each load (Windows .exe version)

### ISSUE THREAD

**Issue by BananaHammock743** [wymangr/blueiris_exporter#2]
**Describe the bug**
In the cmd window I'm getting many `Unable to parse log line:` 
```
2022.11.04 19:35:44 - [console] - Unable to parse log line:
0       4/11/2022 7:33:35.017 PM        FrontDoor               AI: [Objects] person:90% [90,228 429,570] 261ms
2022.11.04 19:36:14 - [console] - Unable to parse log line:
0       4/11/2022 7:34:31.104 PM        NVR-SIDE2-MASK          AI: Alert cancelled [nothing found] 371ms
2022.11.04 19:36:14 - [console] - Unable to parse log line:
```

Attached is 
* Todays BI Log
* Output from v1.0.4 windows .exe with the errors showing

[blueiris_exporter-amd64 v1.0.4 cmd log.txt](https://github.com/wymangr/blueiris_exporter/files/9941249/blueiris_exporter-amd64.v1.0.4.cmd.log.txt)
[blue_iris_log.txt](https://github.com/wymangr/blueiris_exporter/files/9941248/blue_iris_log.txt)

**To Reproduce**
1. With the attached BI Log run blueiris_exporter
2. Wait a few seconds after load, cmd window will then show all the `Unable to parse log line:`  lines

**Expected behavior**
All log items in the BI log can be parsed without error. 

**Screenshots**
![image](https://user-images.githubusercontent.com/48776255/200051880-b8e275fc-1dfa-4e12-a72f-321d05d3a0b8.png)

**Desktop:**
 - OS: Window 10
 - Blue Iris Version: Blue Iris 5.6.2.10 x64 (25/10/2022)
- blueiris_exporter Version 1.0.4 windows cmd 

**Additional context**
N/A

**Comment by wymangr** [comment]
Thank you @BananaHammock743! Found another small issue. Will push up a fix for it now!

**Comment by wymangr** [comment]
Okay, this should fix it! Sorry about that!

https://github.com/wymangr/blueiris_exporter/releases/tag/v1.0.5

**Comment by BananaHammock743** [comment]
Nice. I now only get 3 warnings. 
```
C:\Users\Admin\Downloads>blueiris_exporter-amd64.exe
2022.11.05 08:38:07 - [info] - starting Blue Iris Exporter with the following:
                Log Path: C:\BlueIris\log\
                Metric Path: /metrics
                Port: :2112
2022.11.05 08:38:14 - [console] - Unable to parse log line:
1       4/11/2022 6:05:06.255 AM        NVR-SIDE2               AI: not responding
2022.11.05 08:38:14 - [console] - Unable to parse log line:
1       4/11/2022 8:02:19.281 AM        Gate                    AI: not responding
2022.11.05 08:38:14 - [console] - Unable to parse log line:
1       4/11/2022 8:02:20.641 AM        GATE-MASK               AI: not responding
```

Let me know if the log file would be helpful and I can post.

**Comment by wymangr** [comment]
@BananaHammock743 awesome, thanks for the update! Luckily, I'm not doing anything with those, so (other then filling up the terminal), you aren't loosing any metrics. Unfortunately I couldn't find a list of every possible log entry that Blue Iris will log about 😞.

I will push up an update to ignore that one as well and if you run into any more, please let me know!

**Comment by wymangr** [comment]
Decided to go a different route and I added the not responding errors as a metric. Doing some final testing and should have a new release by the end of the day :)

**Comment by wymangr** [comment]
@BananaHammock743 I have a new release that should fix your warnings as well as add a couple more metrics.

https://github.com/wymangr/blueiris_exporter/releases/tag/v1.1.0

**Comment by wymangr** [comment]
Going to close this out. @BananaHammock743 Feel free to open it back up or create another issue if you have any other problems.
