### ISSUE TITLE
"Unable to parse logfile" regarding RTSP errors[BUG]

### ISSUE THREAD

**Issue by user45876** [wymangr/blueiris_exporter#3]
**Describe the bug**
Getting many lines like this - which mighte well be and are legit errors due to "reasons" - unclear, if you might want to parse them at all, as they are not AI related:

2022.11.17 18:32:01 - [console] - Unable to parse log line:
1       16.11.2022 09:09:14.681 Cam1                 Signal: RTSP: 503 Service Unavailable
2022.11.17 18:32:01 - [console] - Unable to parse log line:
1       16.11.2022 09:09:57.372 Cam1                 Signal: RTSP: 404 Not Found
2022.11.17 18:32:01 - [console] - Unable to parse log line:
1       16.11.2022 09:12:09.922 Cam2         Signal: HTTP: 12002 Timeout

BlueIris on Windows, Cameras are Reolink cameras using the proprietary "Baichuan" protocol, getting an RTSP stream with 'neolink'.

**Comment by wymangr** [comment]
This is from the status metric. I will push up an update to include these! Thanks for the report!

**Comment by wymangr** [comment]
Just added a release that should fix these log errors:
https://github.com/wymangr/blueiris_exporter/releases/tag/v1.1.4
