### ISSUE TITLE
Unable to parse log line [BUG]

### ISSUE THREAD

**Issue by denzelm5** [wymangr/blueiris_exporter#5]
**Describe the bug**
Good Day, i have installed and configure your exported. when i run the tool i get Unable to parse log line command that runs continually 

**To Reproduce**
1. installed the .exe on my c:\ drive
2. opened the command prompt in admin mode.
3. navigated the to the location were the .exe is located.
4. ran this line to start :   blueiris_exporter-amd64.exe --logpath=C:\BlueIris\log
5. confirmed log is writing to /metric directory

**Expected behavior**

**Screenshots**
![image](https://github.com/wymangr/blueiris_exporter/assets/57428868/bd5e5354-af12-4a78-b8fa-77c53cda58e9)
![image](https://github.com/wymangr/blueiris_exporter/assets/57428868/1c723739-eb2f-481d-ad85-afbe6fb4b677)

**Desktop (please complete the following information):**
 - Windows Server 2019 - HP Gen10 Proliant
 - Blue Iris Version 5.7.9.14 (2023/11/01)
- blueiris_exporter Version [e.g. 1.2.0 latest]

**Additional context**
Even though there is the parse error, the data still writes to my influxdb until the exporter tool times out.

**Comment by wymangr** [comment]
Hi @denzelm5 thank you for the report! Would you mind sharing a copy of your latest log file in `C:\BlueIris\log`? I'll dig in and try and get a fix pushed up this week.

**Comment by denzelm5** [comment]
> Hi @denzelm5 thank you for the report! Would you mind sharing a copy of your latest log file in `C:\BlueIris\log`? I'll dig in and try and get a fix pushed up this week.

Hi ,

Thanks for your reply. please see log file below.

Regards

[202311.zip](https://github.com/wymangr/blueiris_exporter/files/13369092/202311.zip)

**Comment by wymangr** [comment]
Thanks for the log, it will make things much easier. At initial glance, it looks like Blue Iris has added some additional logging that the exporter doesn't know how to parse. I've been running mine as a Windows service, so I haven't noticed, but now that I look, it's doing the same thing for me. Feel free to install it as a service if you want to ignore it now as well. 

Good news is, it should be a somewhat easy fix. I'll work on it a bit this week and should have something for you soon!

**Comment by wymangr** [comment]
Testing a fix, if all goes well, I'll push it up tomorrow!

**Comment by wymangr** [comment]
@denzelm5 I've released a fix: https://github.com/wymangr/blueiris_exporter/releases/tag/v1.2.1 as well as a update to the dashboard. Let me know how it goes!

**Comment by denzelm5** [comment]
Hi,
Thank you very much. I have updated the collector, I dont get the error anymore . As this is the first time running the collector , was it suppose to like the below ? I also need to ask, In the grafana server import dashboard, i see the connection requires a Prometheus datasource ? How do you get this working as im writing the data to a bucket....

![image](https://github.com/wymangr/blueiris_exporter/assets/57428868/f2df23a8-1478-499f-8c2d-f94e0c976bd3)

**Comment by wymangr** [comment]
@denzelm5 Looking at the output of the command prompt window on the right, that is what it's supposed to look like. As for the powershell script, I'm guessing you are converting the prometheus metrics to influxdb? Unfortunately, I don't use influxdb, so I can't tell you if that's correct. 

As for the Grafana dashboard, the one I have included in this repo and the one I maintain is for the Prometheus data source as that was the intended use for this exporter. However, I did have one other person who used influxdb and I did create this dashboard as well:

https://grafana.com/grafana/dashboards/17456-blueiris-influx/

It's out dated, and I don't currently have plans on setting up an influxdb to update it, but it could help as a starting point?

**Comment by wymangr** [comment]
@denzelm5 Hey, just wanted to check in and make sure everything is working for you?

**Comment by denzelm5** [comment]
Hi Garret,
Sorry for not providing feedback sooner. The new version worked from BI to Influx, however the Grafana Dashboard for some reason didn't populate all values.


Regards
Denzel
________________________________

**Comment by wymangr** [comment]
@denzelm5, that's good that the exporter is working! Like I said, unfortunately, the dashboard I support is for the Prometheus Data source, so I won't be able to help you much with an Influx dashboard other then the one I provided you. If you end up building a dashboard for influx, let me know and I can share it :)
