### ISSUE TITLE
Missing metrics

### ISSUE THREAD

**Issue by BuxtonCalvin** [wymangr/blueiris_exporter#7]
Hello, I'm using BlueIris 5.9.2.2.  The exporter works without errors except for the below metrics:

**Describe the bug**
The following metrics do not show in the Prometheus status page:
ai_duration_distinct
folder_disk_free
folder_used
hours_used
push_notifications
triggers

The following **do show** in the status page **but are not listed** as metrics on the git splash page:
collector_duration_seconds
exporter_errors

All other splash page listed metrics appear and function normally.

**To Reproduce**
1. Go to Prometheus Status Targets and choose BlueIris exporter.
2. See error

**Expected behavior**
I'd especially like to see the triggers metric

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Blue Iris Version 5.9.2.2
- blueiris_exporter Version latest

Thanks for the exporter, and it works very well.

**Comment by tcernik** [comment]
Hello. I also advocate adding metrics. BlueIris changed the name triggers in the log file. Thank you.

**Comment by wymangr** [comment]
Thanks for the report! I'll take a look and get it fixed. If anyone has an example log file that's having the issue, that would be helpful!

**Comment by BuxtonCalvin** [comment]
Hello @wymangr, did you receive my email with the attached log?  Thx

> Thanks for the report! I'll take a look and get it fixed. If anyone has an example log file that's having the issue, that would be helpful!

**Comment by wymangr** [comment]
@BuxtonCalvin I didn't see the email. What address did you send it to?

**Comment by BuxtonCalvin** [comment]
Long series of numbers @ githup.  It was in the reply to field of the email sent by github, but I imagine it was not a valid address.  I'll attach the file here:
[202406.zip](https://github.com/user-attachments/files/16060970/202406.zip)

**Comment by wymangr** [comment]
@BuxtonCalvin Thank you for the log! It looks like [this ](https://github.com/wymangr/blueiris_exporter/pull/6) PR addresses some of the issue you are having. I'll review and push up anything else that needs fixing. Seems like BI change some things, but my support plan expired, so I'm not on the latest version.

**Comment by wymangr** [comment]
I've released a new version that should fix these issues. Please let me know if there are any other problems. If not, I'll close out this issue.

https://github.com/wymangr/blueiris_exporter/releases/tag/v1.2.3

**Comment by BuxtonCalvin** [comment]
Awesome.  Everything looks really good on my end.  Thanks for the quick turnaround.  One thing you might consider in a future release is changing the counter metric names by appending "counter" to the end of the metric name.  Doing so stops grafana from complaining that metric might not be a counter.  Converting the graph would me easy as I'd just need to update the metric names.
Thx again.
