### ISSUE TITLE
[BUG] 'panic: runtime error: index out of range' parsing delete line

### ISSUE THREAD

**Issue by slim-bean** [wymangr/blueiris_exporter#9]
**Describe the bug**

Hello!
Installed this awesome tool today and I think I found a bug.

```
panic: runtime error: index out of range [2] with length 0

goroutine 100 [running]:
github.com/wymangr/blueiris_exporter/blueiris.findObject({0xc000478460, 0x50})
        /home/runner/work/blueiris_exporter/blueiris_exporter/blueiris/blueirisMetrics.go:440 +0x1838
github.com/wymangr/blueiris_exporter/blueiris.BlueIris(0x0?, {0xc000170e00, 0x2, {0x592c00, 0xb}, 0x1, {0xc0000da160, 0x16, 0x16}, 0x5ccb10, ...}, ...)
        /home/runner/work/blueiris_exporter/blueiris_exporter/blueiris/blueirisMetrics.go:112 +0x62a
main.CollectMetrics(0x103405?, 0xc00035dfd0?, {0xc000170e00, 0x2, {0x592c00, 0xb}, 0x1, {0xc0000da160, 0x16, 0x16}, ...}, ...)
        /home/runner/work/blueiris_exporter/blueiris_exporter/metrics.go:113 +0x34b
created by main.(*ExporterBlueIris).Collect
        /home/runner/work/blueiris_exporter/blueiris_exporter/blueiris_exporter.go:38 +0x285
```

**To Reproduce**

This seems to be the offending log line:

```
0 	11/10/2024 5:32:31.125 PM	Alerts              	Delete: nothing to do 1 locked
```

I think I may have an alert or clip marked as locked so it can't be deleted and seems like this doesn't get regexed properly?

**Comment by wymangr** [comment]
@slim-bean thanks for the report! I'll take a look!

**Comment by wymangr** [comment]
Looks like I can duplicate the issue with the line you posted above and it's a pretty simple fix. Would you mind sharing your log file to make sure that's the only issue before I commit?

**Comment by slim-bean** [comment]
glad it's an easy fix!

my log file has some usernames in it and maybe some other data I'd rather not share publicly. 

If you have a branch with your fix though I'd be happy to build a version locally and run my file through it to make sure it works!

**Comment by wymangr** [comment]
@slim-bean no problem at all. Let me throw together a release with my changes and you can try it out.

**Comment by wymangr** [comment]
Let me know if this fixes it for you :)
https://github.com/wymangr/blueiris_exporter/releases/tag/v1.3.3

**Comment by slim-bean** [comment]
Been running fine for a couple days now! I'd say it's fixed! thank you!
